# Generated by Django 3.0.6 on 2021-07-20 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogtbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('introduction', models.CharField(max_length=300, null=True)),
                ('description', models.TextField()),
                ('created_date', models.DateField()),
                ('image', models.FileField(null=True, upload_to='blogs')),
                ('status', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Usertbl')),
            ],
        ),
    ]
